services:
  - type: web
    name: material-search-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        value: product
      - key: MONGODB_COLLECTION
        value: products
      - key: PYTHON_VERSION
        value: 3.11.0
